import { ConfigService } from '@nestjs/config';
import { SequelizeModuleAsyncOptions } from '@nestjs/sequelize';
import { getEnv, getIntEnv } from './helpers';
import {
  AuthTokens,
  Permissions,
  RolePermissions,
  Users,
  Authors,
  AuthorFollows,
  PublishingHouses,
  Books,
  AuthCodeEvents,
  AuthorRewardPercents,
  BookCharacters,
  UserBookReviews,
  UserBookPurchase,
  UserFavoriteBooks,
  BookReviews,
  CheckLogs,
  UserBookCharacters,
  Roles,
  AuthorPosts,
  AuthorPostImages,
  AuthorPostLikes,
  AuthorPostComments,
  AuthorPostReposts,
  BookGenres,
  BookGenreMeta,
  BookTopRating,
  NotificationSettings,
  ReadingSettings,
  Bookmarks,
  AuthorVerifications,
  NewsletterSubscriptions,
  MagazineArticles,
} from 'libs/models/index';

export const getSequelizeConfig: SequelizeModuleAsyncOptions = {
  useFactory: (configService: ConfigService) => ({
    dialect: 'postgres',
    logging: false,
    benchmark: true,
    host: getEnv('DB_HOST', configService),
    port: getIntEnv('DB_PORT', configService),
    username: getEnv('DB_USER', configService),
    password: getEnv('DB_PASS', configService),
    database: getEnv('DB_NAME', configService),
    autoLoadModels: true,
    synchronize: getEnv('ENV', configService) === 'test',
    define: {
      underscored: true,
    },
    sync: {
      alter: true,
    },

    models: [
      Users,
      Permissions,
      RolePermissions,
      AuthTokens,
      AuthCodeEvents,
      Authors,
      AuthorFollows,
      AuthorRewardPercents,
      PublishingHouses,
      Books,
      BookCharacters,
      UserBookReviews,
      UserBookPurchase,
      UserFavoriteBooks,
      BookReviews,
      CheckLogs,
      UserBookCharacters,
      Roles,
      AuthorPosts,
      AuthorPostImages,
      AuthorPostLikes,
      AuthorPostComments,
      AuthorPostReposts,
      BookGenres,
      BookGenreMeta,
      BookTopRating,
      NotificationSettings,
      ReadingSettings,
      Bookmarks,
      AuthorVerifications,
      NewsletterSubscriptions,
      MagazineArticles,
    ],
  }),
  inject: [ConfigService],
  // imports: [ConfigModule],
};
